@startmindmap Classes

*[#ffff33]: <b>Вложенные классы
    <b>(Nested classes);
**[#b2ff66]: <b>Статические вложенные классы
        <b> (Static nested classes);
**[#FFD765]: <b>Нестатические вложенные
    <b>(=внутренние) классы
        <b> (Inner classes);

***[#ff9999]: <b>Просто внутренние классы
    <b> (Inner classes);
***[#ff99cc]: <b>Локальные внутренние классы
    <b> (Local inner classses);
***[#99ffff]: <b>Анонимные внутренние классы
    <b> (Anonymous inner classes);
@endmindmap