-- dropping enum types
DROP TYPE IF EXISTS CLIMATE_ENUM CASCADE;
DROP TYPE IF EXISTS GOVERNMENT_ENUM CASCADE;
DROP TYPE IF EXISTS STANDARD_OF_LIVING_ENUM CASCADE;

-- dropping tables 
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS Coordinates CASCADE;
DROP TABLE IF EXISTS Human CASCADE;
DROP TABLE IF EXISTS City CASCADE;
DROP TABLE IF EXISTS Creator CASCADE;

-- dropping domains
DROP DOMAIN IF EXISTS positive_integer CASCADE;
DROP DOMAIN IF EXISTS area_constraint CASCADE;
DROP DOMAIN IF EXISTS population_constraint CASCADE;

-- creating enums if they're exists
CREATE TYPE CLIMATE_ENUM AS ENUM ('TROPICAL_SAVANNA', 'OCEANIC', 'STEPPE');
CREATE TYPE GOVERNMENT_ENUM AS ENUM ('ANARCHY', 'GERONTOCRACY', 'DEMARCHY', 'COMMUNISM', 'NOOCRACY');
CREATE TYPE STANDARD_OF_LIVING_ENUM AS ENUM ('ULTRA_HIGH', 'VERY_HIGH', 'HIGH', 'ULTRA_LOW', 'NIGHTMARE');

-- create domain's
CREATE DOMAIN positive_integer AS INTEGER
CHECK (VALUE > 0);

CREATE DOMAIN area_constraint AS positive_integer;
CREATE DOMAIN population_constraint AS positive_integer;

-- creating tables if they're exists
CREATE TABLE IF NOT EXISTS "User" (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    passwd_hash TEXT NOT NULL,
    passwd_salt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Coordinates (
    id SERIAL PRIMARY KEY,
    x INTEGER CHECK (VALUE < 499) NOT NULL,
    y DOUBLE PRECISION CHECK (VALUE > -274) NOT NULL
);

CREATE TABLE IF NOT EXISTS Human (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS City (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    coordinates_id INTEGER REFERENCES Coordinates(id) ON DELETE RESTRICT NOT NULL UNIQUE,
    creation_date TIMESTAMP NOT NULL, 
    area area_constraint,
    population population_constraint NOT NULL,
    meters_above_sea_level DOUBLE PRECISION,
    climate CLIMATE_ENUM NOT NULL,
    government GOVERNMENT_ENUM NOT NULL,
    governor_id INTEGER REFERENCES Human(id) ON DELETE RESTRICT NOT NULL UNIQUE,
    standardOfLiving STANDARD_OF_LIVING_ENUM NOT NULL
);

CREATE TABLE IF NOT EXISTS Creator (
    user_id BIGINT DEFAULT 1 REFERENCES "User"(id) ON DELETE SET DEFAULT NOT NULL,
    city_id BIGINT REFERENCES City(id) ON DELETE CASCADE NOT NULL UNIQUE,
    PRIMARY KEY (user_id, city_id)
);

