@startuml ClassesModel

enum CosmicObjectType {
    STAR
    ASTEROID
    PLANET
    GALAXY
    SATALITE
}

interface Lightable {
    + double light()
}

interface Reflectable {
    + double reflect(Light otherLight)
}   

interface Viewable {
    + String getView(CosmicObject viewPoint)
}

note bottom of Viewable
    This interface is used for objects, that can be seen by humans
    from other cosmic objects.
end note

CosmicObject -- CosmicObjectType
abstract class CosmicObject implements Viewable {
    # CosmicObjectType type
    # int brightness
    # String name
    # double radius
    # double mass

    + CosmicObject(String name, double radius, double mass)

    + CosmicObjectType getType()
    + int getBrightness()
    + Strign getName()
}

note bottom of CosmicObject
    This is the base class for all objects in the universe.
end note

class Star extends CosmicObject implements Lightable {
    # CosmicObjectType type = STAR
    + Star(String name, double radius, double mass, int brightness)

    + String light()
}

class Sun extends Star {
    # type = STAR
    # name = Sun
    # brightness = 50
    # radius = 696 340
    # mass = 1.98892 * 10^30
    + Sun()
}


class Earth extends CosmicObject implements Reflectable {
    # type = PLANET
    # brightness = 2
    # name = Earth
    # mass = 5.9742 * 10^24
    # radius = 6371

    + Earth()
    + Light reflect(Light otherLight)
}


class Moon extends CosmicObject implements Reflectable {
    # type = SATALITE
    # brightness = 1
    # name = Moon
    # mass = 7.36 * 10^22
    # radius = 1737.4
    + Moon()
    + Light reflect(Light otherLight)
}

class Sky implements Viewable {
    # CosmicObject[] objects

    + String getView(CosmicObject viewPoint)
}

abstract class Human implements Viewable {
    # String name
    # CosmicObject location

    + String getName()
    + CosmicObject getLocation()
    + see(Viewable target)
    + read()
    + write()
    + draw()
}

note top of Human
    This is the base class for all humans in the universe.
    see() methods call getView() method of class Viewable object
    Method read(), write() and draw() can check brightness of object before running.
end note

class Znayka extends Human {
    # name = Znayka
    + Znayka()
    + see(Viewable target)
    + read()
    + write()
    + draw()
}

note top of Fuksy
    I find out, that Fuksy, Seledochka and ProfessorZvizdochkin are Neznayka's companions.
end note

class Fuksy extends Human {
    # name = Fuksy
    + Fuksy()
    + see(Viewable target)
    + read()
    + write()
    + draw()
}

class Seledochka extends Human {
    # name = Seledochka
    + Seledochka()
    + see(Viewable target)
    + read()
    + write()
    + draw()
}

class ProfessorZvizdochkin extends Human {
    # name = ProfessorZvizdochkin
    + ProfessorZvizdochkin()
    + see(Viewable target)
    + read()
    + write()
    + draw()
}

@enduml